[package]
name = "flux"
version = "0.0.1"
authors = ["Chris Gibson <cgibson@mrvoxel.com>"]

[dependencies.nalgebra]
version = "0.16.5"
features = ["serde-serialize"]

[dependencies.serde]
version = "1.0.79"

[dependencies]
serde_derive = "1.0.79"
serde_json = "1.0.32"